 version: "2"
 services: 
    web:
        build: .
        restart: always
        ports: 
        - "8000:3000"
        depends_on: 
        - "mongo"
    mongo:
        image: mongo
        ports: 
        - "27017:27017"
    